app-name: "Node.js test service"

servers:
  my-http-server:
    hosts:
      - "127.0.0.1"
    port: 80
    protocol: "http"
    endpoints:
      serve-static:
        location: "/"
        methods:
          get:
            handler: "serveStatic"

      session:
        location: "/session"
        methods:
          get:
            handler: "newSession"

          post:
            handler: "validateSession"

          delete:
            handler: "deleteSession"

      events:
        location: "/events"
        methods:
          post:
            handler: "callService"


